---

include:
  - project: nci-gdc/gitlab-templates
    ref: 0.2.1
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml
      - templates/common/python.yaml

tox:
  stage: test
  parallel:
    matrix:
      - PYTHON_VERSION: ['3.7', '3.8']
  image: ${BASE_CONTAINER_REGISTRY}/python${PYTHON_VERSION}-builder:${BASE_CONTAINER_VERSION}
  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:feat_dev-1924-postgres-init-script-3673ef90
      alias: postgres
  tags:
    - dind
  variables:
    # these are for postgres docker
    POSTGRES_HOST_AUTH_METHOD: trust
    PG_HOST: postgres
    PG_INIT_SQL: |
      create user test with superuser password 'test';
      create database automated_test with owner test;
      create database dev_models with owner test;
  before_script:
    - !reference [.load_github_key, script]
    - pip install "tox<4"
  script:
    - tox -r -e py


# used by release
.python_versions:
  parallel:
    matrix:
      - BUILD_PY_VERSION: [python3.7]
      - RELEASE_PY_VERSION: [python3.7]

release:
  before_script:
    - git fetch --unshallow || true
