---

include:
  - project: nci-gdc/gitlab-templates
    ref: 0.2.1
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml
      - templates/common/python.yaml

tox:
  parallel:
    matrix:
      - BUILD_PY_VERSION: [python3.7, python3.8, python3.9]
  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:2.3.2
      alias: postgres
  variables:
    # these are for postgres docker
    POSTGRES_HOST_AUTH_METHOD: trust
    PG_HOST: postgres
    PG_INIT_SQL: |
      create user test with superuser password 'test';
      create database automated_test with owner test;
      create database dev_models with owner test;
  before_script:
    - !reference [.load_github_key, script]
    - pip install "tox<4"
  script:
    - tox -r -e py


# used by release
release:
  before_script:
    - git fetch --unshallow || true
